dukecity_command_scheduler_list:
    path:  /command-scheduler/list
    defaults: { _controller: Dukecity\CommandSchedulerBundle\Controller\ListController::indexAction }

dukecity_command_scheduler_monitor:
    path:  /command-scheduler/monitor
    defaults: { _controller: Dukecity\CommandSchedulerBundle\Controller\ListController::monitorAction }

dukecity_command_scheduler_action_toggle:
    path:  /command-scheduler/action/toggle/{id}
    defaults: { _controller: Dukecity\CommandSchedulerBundle\Controller\ListController::toggleAction }

dukecity_command_scheduler_action_remove:
    path:  /command-scheduler/action/remove/{id}
    defaults: { _controller: Dukecity\CommandSchedulerBundle\Controller\ListController::removeAction }

dukecity_command_scheduler_action_execute:
    path:  /command-scheduler/action/execute/{id}
    defaults: { _controller: Dukecity\CommandSchedulerBundle\Controller\ListController::executeAction }

dukecity_command_scheduler_action_unlock:
    path:  /command-scheduler/action/unlock/{id}
    defaults: { _controller: Dukecity\CommandSchedulerBundle\Controller\ListController::unlockAction }

dukecity_command_scheduler_detail_index:
    path:  /command-scheduler/detail/view/
    defaults: { _controller: Dukecity\CommandSchedulerBundle\Controller\DetailController::indexAction }

dukecity_command_scheduler_detail_edit:
    path:  /command-scheduler/detail/edit/{scheduledCommandId}
    defaults: { _controller: Dukecity\CommandSchedulerBundle\Controller\DetailController::initEditScheduledCommandAction }

dukecity_command_scheduler_detail_new:
    path:  /command-scheduler/detail/new
    defaults: { _controller: Dukecity\CommandSchedulerBundle\Controller\DetailController::initNewScheduledCommandAction }

dukecity_command_scheduler_detail_save:
    path:  /command-scheduler/detail/save
    defaults: { _controller: Dukecity\CommandSchedulerBundle\Controller\DetailController::saveAction }
