jmose_command_scheduler_list:
    path:  /command-scheduler/list
    defaults: { _controller: JMose\CommandSchedulerBundle\Controller\ListController::indexAction }

jmose_command_scheduler_monitor:
    path:  /command-scheduler/monitor
    defaults: { _controller: JMose\CommandSchedulerBundle\Controller\ListController::monitorAction }

jmose_command_scheduler_action_toggle:
    path:  /command-scheduler/action/toggle/{id}
    defaults: { _controller: JMose\CommandSchedulerBundle\Controller\ListController::toggleAction }

jmose_command_scheduler_action_remove:
    path:  /command-scheduler/action/remove/{id}
    defaults: { _controller: JMose\CommandSchedulerBundle\Controller\ListController::removeAction }

jmose_command_scheduler_action_execute:
    path:  /command-scheduler/action/execute/{id}
    defaults: { _controller: JMose\CommandSchedulerBundle\Controller\ListController::executeAction }

jmose_command_scheduler_action_unlock:
    path:  /command-scheduler/action/unlock/{id}
    defaults: { _controller: JMose\CommandSchedulerBundle\Controller\ListController::unlockAction }

jmose_command_scheduler_detail_index:
    path:  /command-scheduler/detail/view/
    defaults: { _controller: JMose\CommandSchedulerBundle\Controller\DetailController::indexAction }

jmose_command_scheduler_detail_edit:
    path:  /command-scheduler/detail/edit/{id}
    defaults: { _controller: JMose\CommandSchedulerBundle\Controller\DetailController::edit }

jmose_command_scheduler_detail_new:
    path:  /command-scheduler/detail/edit
    defaults: { _controller: JMose\CommandSchedulerBundle\Controller\DetailController::edit }
