language: php

matrix:
    include:
        - php: 8.0

    allow_failures:
        - php: nightly

branches:
    only:
        - master
        - /^\d+\.\d+$/

before_script:
    - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d && echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - mkdir -p build/logs
    - vendor/bin/phpunit

# Run coveralls
after_success:
    - php vendor/bin/php-coveralls -v

notifications:
    email: info@sky-scripts.de
