# .github/workflows/code_checks.yaml
name: Code_Checks

on:
  pull_request: null
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.0']

    name: PHP ${{ matrix.php }} tests
    steps:
      # basically git clone
      - uses: actions/checkout@v2

      # use PHP of specific version
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pcov
          coverage: pcov # none, disable xdebug, pcov

      # if we 2 steps like this, we can better see if composer failed or tests
      -   run: composer install --no-progress
      -   run: vendor/bin/phpunit


  cs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none # disable xdebug, pcov
      - run: composer install --no-progress
      - run: composer cscheck


  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none # disable xdebug, pcov
      - run: composer install --no-progress
      - run: composer phpstan


  code_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: pcov

      - run: composer install --no-progress

      # https://kizu514.com/blog/pcov-is-better-than-phpdbg-and-xdebug-for-code-coverage/
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
