# .github/workflows/code_coverage.yaml
name: Code_Coverage

on:
  pull_request: null
  push:
    branches:
      - master

jobs:
  code_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: pcov

      # Coveralls.io
      # https://github.com/php-coveralls/php-coveralls
      - run: composer require --dev php-coveralls/php-coveralls:^2.4
      - run: composer install --no-progress

      - run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

      #- run: vendor/bin/phpunit --coverage-php build/logs/rules.cov
      - run: vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v

#- run: lcov --no-external --capture --quiet --output-file coverage.info

      # https://kizu514.com/blog/pcov-is-better-than-phpdbg-and-xdebug-for-code-coverage/
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}